version: '3.7'

services:
  recruitment-task-75104832-7773-4dee-997a-84903fc5e0b7:
    container_name: recruitment-task-75104832-7773-4dee-997a-84903fc5e0b7
    build:
      context: .
      dockerfile: dev.Dockerfile
      args:
        - user_id=$UID
        - group_id=$GID
        - user=$USER
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - recruitment-task-75104832-7773-4dee-997a-84903fc5e0b7-database
    links:
      - recruitment-task-75104832-7773-4dee-997a-84903fc5e0b7-database
    working_dir: /app
    command: npm run start:debug

  recruitment-task-75104832-7773-4dee-997a-84903fc5e0b7-database:
    container_name: recruitment-task-75104832-7773-4dee-997a-84903fc5e0b7-database
    image: library/postgres:13.4-alpine
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: recruitment-task-75104832-7773-4dee-997a-84903fc5e0b7-database
        target: /var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

volumes:
  recruitment-task-75104832-7773-4dee-997a-84903fc5e0b7-database:
